import React from 'react';

const TokensPage = () => {
  return (
    <div>
      <h3 style={{ marginBottom: '20px', marginTop: '40px' }}>Design Tokens</h3>
      <h4 style={{ marginBottom: '20px', marginTop: '40px' }}>Headings</h4>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody id="properties-list">
          <tr>
            <td>
              <code>--l-border-width-default</code>
            </td>
            <td>
              <span>1px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-breakpoint-extralarge</code>
            </td>
            <td>
              <span>1280px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-breakpoint-large</code>
            </td>
            <td>
              <span>1024px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-breakpoint-medium</code>
            </td>
            <td>
              <span>768px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-breakpoint-small</code>
            </td>
            <td>
              <span>576px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-blue-10</code>
            </td>
            <td style={{ padding: '0 4px', background: '#e6f0fd' }}>
              <span>#e6f0fd</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-blue-100</code>
            </td>
            <td style={{ padding: '0 4px', background: '#0e6aed' }}>
              <span>#0e6aed</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-blue-125</code>
            </td>
            <td style={{ padding: '0 4px', background: '#1a5ade' }}>
              <span>#1a5ade</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-blue-150</code>
            </td>
            <td style={{ padding: '0 4px', background: '#2437bf' }}>
              <span>#2437bf</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-blue-25</code>
            </td>
            <td style={{ padding: '0 4px', background: '#c3dafb' }}>
              <span>#c3dafb</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-blue-5</code>
            </td>
            <td style={{ padding: '0 4px', background: '#f6f9ff' }}>
              <span>#f6f9ff</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-blue-50</code>
            </td>
            <td style={{ padding: '0 4px', background: '#86b5f8' }}>
              <span>#86b5f8</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-blue-75</code>
            </td>
            <td style={{ padding: '0 4px', background: '#4b91f5' }}>
              <span>#4b91f5</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-blue-90</code>
            </td>
            <td style={{ padding: '0 4px', background: '#267af2' }}>
              <span>#267af2</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-border</code>
            </td>
            <td style={{ padding: '0 4px', background: '#e6e9ec' }}>
              <span>#e6e9ec</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-darkblue-10</code>
            </td>
            <td style={{ padding: '0 4px', background: '#e6e9ec' }}>
              <span>#e6e9ec</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-darkblue-100</code>
            </td>
            <td style={{ padding: '0 4px', background: '#092c47' }}>
              <span>#092c47</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-darkblue-25</code>
            </td>
            <td style={{ padding: '0 4px', background: '#c1cad1' }}>
              <span>#c1cad1</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-darkblue-5</code>
            </td>
            <td style={{ padding: '0 4px', background: '#f5f7f8' }}>
              <span>#f5f7f8</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-darkblue-50</code>
            </td>
            <td style={{ padding: '0 4px', background: '#8495a3' }}>
              <span>#8495a3</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-darkblue-75</code>
            </td>
            <td style={{ padding: '0 4px', background: '#476175' }}>
              <span>#476175</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-darkblue-90</code>
            </td>
            <td style={{ padding: '0 4px', background: '#22445f' }}>
              <span>#22445f</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-disabled-color</code>
            </td>
            <td style={{ padding: '0 4px', background: '#476175' }}>
              <span>#476175</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-disabled-fill</code>
            </td>
            <td style={{ padding: '0 4px', background: '#e6e9ec' }}>
              <span>#e6e9ec</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-disabled-stroke</code>
            </td>
            <td style={{ padding: '0 4px', background: '#e6e9ec' }}>
              <span>#e6e9ec</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-gray-0</code>
            </td>
            <td style={{ padding: '0 4px', background: '#253843' }}>
              <span>#253843</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-gray-1</code>
            </td>
            <td style={{ padding: '0 4px', background: '#55646d' }}>
              <span>#55646d</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-gray-2</code>
            </td>
            <td style={{ padding: '0 4px', background: '#959fa4' }}>
              <span>#959fa4</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-gray-3</code>
            </td>
            <td style={{ padding: '0 4px', background: '#999fa3' }}>
              <span>#999fa3</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-gray-4</code>
            </td>
            <td style={{ padding: '0 4px', background: '#c4c5c6' }}>
              <span>#c4c5c6</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-gray-5</code>
            </td>
            <td style={{ padding: '0 4px', background: '#d8dee1' }}>
              <span>#d8dee1</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-gray-6</code>
            </td>
            <td style={{ padding: '0 4px', background: '#f2f2f2' }}>
              <span>#f2f2f2</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-gray-7</code>
            </td>
            <td style={{ padding: '0 4px', background: '#f3f6f8' }}>
              <span>#f3f6f8</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-gray-8</code>
            </td>
            <td style={{ padding: '0 4px', background: '#fcfdfd' }}>
              <span>#fcfdfd</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-green-10</code>
            </td>
            <td style={{ padding: '0 4px', background: '#c4efe1' }}>
              <span>#c4efe1</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-green-100</code>
            </td>
            <td style={{ padding: '0 4px', background: '#13bf87' }}>
              <span>#13bf87</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-green-125</code>
            </td>
            <td style={{ padding: '0 4px', background: '#10a474' }}>
              <span>#10a474</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-green-25</code>
            </td>
            <td style={{ padding: '0 4px', background: '#c4efe1' }}>
              <span>#c4efe1</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-green-5</code>
            </td>
            <td style={{ padding: '0 4px', background: '#e7f8f3' }}>
              <span>#e7f8f3</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-green-50</code>
            </td>
            <td style={{ padding: '0 4px', background: '#89dfc3' }}>
              <span>#89dfc3</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-green-75</code>
            </td>
            <td style={{ padding: '0 4px', background: '#4ecfa5' }}>
              <span>#4ecfa5</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-overlay</code>
            </td>
            <td style={{ padding: '0 4px', background: '#092c4726' }}>
              <span>#092c4726</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-purple-10</code>
            </td>
            <td style={{ padding: '0 4px', background: '#ece5fc' }}>
              <span>#ece5fc</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-purple-100</code>
            </td>
            <td style={{ padding: '0 4px', background: '#4800e3' }}>
              <span>#4800e3</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-purple-125</code>
            </td>
            <td style={{ padding: '0 4px', background: '#3b00bb' }}>
              <span>#3b00bb</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-purple-25</code>
            </td>
            <td style={{ padding: '0 4px', background: '#d1bff8' }}>
              <span>#d1bff8</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-purple-50</code>
            </td>
            <td style={{ padding: '0 4px', background: '#a37ff1' }}>
              <span>#a37ff1</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-purple-75</code>
            </td>
            <td style={{ padding: '0 4px', background: '#7640ea' }}>
              <span>#7640ea</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-red-10</code>
            </td>
            <td style={{ padding: '0 4px', background: '#fcebe7' }}>
              <span>#fcebe7</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-red-100</code>
            </td>
            <td style={{ padding: '0 4px', background: '#e63817' }}>
              <span>#e63817</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-red-125</code>
            </td>
            <td style={{ padding: '0 4px', background: '#c72f12' }}>
              <span>#c72f12</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-red-25</code>
            </td>
            <td style={{ padding: '0 4px', background: '#f7ccc4' }}>
              <span>#f7ccc4</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-red-50</code>
            </td>
            <td style={{ padding: '0 4px', background: '#ef9a89' }}>
              <span>#ef9a89</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-red-75</code>
            </td>
            <td style={{ padding: '0 4px', background: '#e7684f' }}>
              <span>#e7684f</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-yellow-10</code>
            </td>
            <td style={{ padding: '0 4px', background: '#fff8e7' }}>
              <span>#fff8e7</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-yellow-100</code>
            </td>
            <td style={{ padding: '0 4px', background: '#ffc118' }}>
              <span>#ffc118</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-yellow-125</code>
            </td>
            <td style={{ padding: '0 4px', background: '#f9ae00' }}>
              <span>#f9ae00</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-yellow-25</code>
            </td>
            <td style={{ padding: '0 4px', background: '#ffefc5' }}>
              <span>#ffefc5</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-yellow-50</code>
            </td>
            <td style={{ padding: '0 4px', background: '#ffe08b' }}>
              <span>#ffe08b</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-color-yellow-75</code>
            </td>
            <td style={{ padding: '0 4px', background: '#ffd152' }}>
              <span>#ffd152</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-family-icons</code>
            </td>
            <td>
              <span>"Font Awesome 6 Pro"</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-family-text</code>
            </td>
            <td>
              <span>"Open Sans",Helvetica,Arial,sans-serif</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-lineheight-1</code>
            </td>
            <td>
              <span>14px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-lineheight-2</code>
            </td>
            <td>
              <span>18px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-lineheight-3</code>
            </td>
            <td>
              <span>20px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-lineheight-4</code>
            </td>
            <td>
              <span>24px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-lineheight-5</code>
            </td>
            <td>
              <span>27px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-lineheight-6</code>
            </td>
            <td>
              <span>30px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-lineheight-7</code>
            </td>
            <td>
              <span>34px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-lineheight-8</code>
            </td>
            <td>
              <span>44px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-lineheight-9</code>
            </td>
            <td>
              <span>56px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-size-large</code>
            </td>
            <td>
              <span>24px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-size-larger</code>
            </td>
            <td>
              <span>32px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-size-largest</code>
            </td>
            <td>
              <span>40px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-size-medium</code>
            </td>
            <td>
              <span>20px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-size-small</code>
            </td>
            <td>
              <span>16px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-size-smaller</code>
            </td>
            <td>
              <span>14px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-size-smallest</code>
            </td>
            <td>
              <span>13px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-weight-bold</code>
            </td>
            <td>
              <span>800</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-weight-light</code>
            </td>
            <td>
              <span>200</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-weight-regular</code>
            </td>
            <td>
              <span>400</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-font-weight-semibold</code>
            </td>
            <td>
              <span>600</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-radius-1</code>
            </td>
            <td>
              <span>3px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-radius-full</code>
            </td>
            <td>
              <span>9999px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-shadow-1</code>
            </td>
            <td>
              <span>#c1cad10 1px 4px 0</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-space-1</code>
            </td>
            <td>
              <span>4px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-space-10</code>
            </td>
            <td>
              <span>40px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-space-2</code>
            </td>
            <td>
              <span>8px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-space-3</code>
            </td>
            <td>
              <span>12px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-space-4</code>
            </td>
            <td>
              <span>16px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-space-5</code>
            </td>
            <td>
              <span>20px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-space-6</code>
            </td>
            <td>
              <span>24px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-space-7</code>
            </td>
            <td>
              <span>28px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-space-8</code>
            </td>
            <td>
              <span>32px</span>
            </td>
          </tr>
          <tr>
            <td>
              <code>--l-space-9</code>
            </td>
            <td>
              <span>36px</span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};

export default TokensPage;
