import React from 'react';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import '@ant-design/v5-patch-for-react-19';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className={openSans.className}>{children}</body>
    </html>
  );
}

export default RootLayout;
